IMPORT FROM CSV FILE 'R.csv' into R(A1 string);
IMPORT FROM CSV FILE 'S.csv' into S(A1 string);
IMPORT FROM CSV FILE 'T.csv' into T(A1 string, state string);
SELECT * FROM R NATURAL JOIN T;
SELECT * FROM R JOIN T USING (A1);
SELECT * FROM S NATURAL JOIN T;
SELECT * FROM S JOIN T USING (A1);
SELECT * FROM DIFF (SELECT * FROM R JOIN T USING (A1)), (SELECT * FROM S JOIN T USING (A1)) ON state WITH MIN SUPPORT 0.01;
SELECT * FROM DIFF (SELECT * FROM R NATURAL JOIN T), (SELECT * FROM S NATURAL JOIN T) ON state WITH MIN SUPPORT 0.01;
