/*
 * Component - QuerySummary
 * ########################
 * The query summary gives a English summary of a SQL query generated by the query wizard.
 * Used in Explore and History tabs.
 */

import { Component, OnInit, Input } from '@angular/core';
import { QueryService } from '../query.service'

@Component({
  selector: 'app-query-summary',
  templateUrl: './query-summary.component.html',
  styleUrls: ['./query-summary.component.css']
})
export class QuerySummaryComponent implements OnInit {
  @Input() id: number;
  private metric: string;
  private attributes: string;
  private support: number;
  private ratio: number;
  private percentile: number;

  constructor(private queryService: QueryService) { }

  ngOnInit() {
    let key = this.id.toString();
    this.updateSummary(this.queryService.queries.get(key));
  }

  /*
   * Updates query information
   */
  private updateSummary(query) {
    this.metric = query["metric"];
    this.attributes = Array.from(query["attributes"]).join(", ");
    this.support = query["minSupport"];
    this.ratio = query["minRatioMetric"];
    this.percentile = query["percentile"];
  }

}
