IMPORT FROM CSV FILE 'table_R.csv' into R(A0 string);
IMPORT FROM CSV FILE 'table_S.csv' into S(A0 string);
IMPORT FROM CSV FILE 'table_T.csv' into T(A0 string, A1 string, A2 string, A3 string, A4 string);
SELECT * FROM R NATURAL JOIN T;
SELECT * FROM R JOIN T USING (A0);
SELECT * FROM S NATURAL JOIN T;
SELECT * FROM S JOIN T USING (A0);
SELECT * FROM DIFF (SELECT * FROM R JOIN T USING (A0)), (SELECT * FROM S JOIN T USING (A0)) ON A1, A2, A3, A4 WITH MIN SUPPORT 0.01 ORDER BY global_ratio DESC INTO OUTFILE 'correct.csv';
SELECT * FROM DIFF (SELECT * FROM R NATURAL JOIN T), (SELECT * FROM S NATURAL JOIN T) ON A1, A2, A3, A4 WITH MIN SUPPORT 0.01 ORDER BY global_ratio DESC INTO OUTFILE 'output.csv';
